### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_getBearerToken'

### ISSUE THREAD

**Issue by Thuliumify** [Aspect1103/Lavapy#3]
I'm having a problem trying to create a node in lavapy.

Task exception was never retrieved
future: <Task finished name='Task-1' coro=<initialiseNodes() done, defined at C:\Users\Admin\Desktop\spaced_retention\testing discord.py:276> exception=AttributeError("'NoneType' object has no attribute '_getBearerToken'")>
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\spaced_retention\testing discord.py", line 282, in initialiseNodes
    await lavapy.NodePool.createNode(client, "127.0.0.1", 2333, "youshallnotpass",identifier='TEST',region=discord.VoiceRegion.singapore)
  File "I:\Python\Python310\lib\site-packages\lavapy\pool.py", line 135, in createNode
    await node.spotifyClient._getBearerToken()
AttributeError: 'NoneType' object has no attribute '_getBearerToken'

Help is appreciated 👍🏿

**Comment by Aspect1103** [comment]
The PyPi version is not the same version as this version so it doesn't include the Spotify extension. Also I'm still actively developing this branch so its very unstable right now.
