### ISSUE TITLE
nextcord version?

### ISSUE THREAD

**Issue by rexwu1104** [Aspect1103/Lavapy#5]
Is it have nextcord version, because I get this error.
![image](https://user-images.githubusercontent.com/44058270/148498894-7bb9e1b2-ea3f-4618-9c3d-2d937d851755.png)

I change a little file of your package in [here](https://github.com/rexwu1104/NextLava/tree/nextcord-version)
can you update to nextcord version? please.

**Comment by rexwu1104** [comment]
I upload a new package at pypi, it name 'nextlava', I just change the discord.py to nextcord, if you changed your package, I will remove it, the reason of I upload is I wnat to use now, sorry.

**Comment by Aspect1103** [comment]
Hi, I wanted to be able to support either discord.py, pycord or nextcord so I intentionally using the discord namespace (which iirc all 3 packages use).

**Comment by rexwu1104** [comment]
but, just like you see, i get an error from import discord.VoiceProtocol

**Comment by rexwu1104** [comment]
can I build a version for nextcord (Exclusive)?

**Comment by Aspect1103** [comment]
> but, just like you see, i get an error from import discord.VoiceProtocol

Using pip to install the latest version of nextcord should install the discord namespace as well. Are you sure you installed it correctly?

**Comment by rexwu1104** [comment]
> > but, just like you see, i get an error from import discord.VoiceProtocol
> 
> Using pip to install the latest version of nextcord should install the discord namespace as well. Are you sure you installed it correctly?

yes

**Comment by Aspect1103** [comment]
You can build your own version of the library (it is MIT), but it should work with nextcord. For a test (in a virtual environment), I installed lavapy then uninstall discord.py and then install nextcord.

**Comment by rexwu1104** [comment]
I tried.
I use original lavapy version (the version will install discord.py), and nextcord said 'discord exist in nextcord'.

**Comment by Aspect1103** [comment]
Did you make sure to uninstall discord.py and reinstall nextcord? Since uninstalling discord.py will remove the discord namespace but (if you installed nextcord before lavapy) the nextcord namespace is still there.

**Comment by rexwu1104** [comment]
thanks, it solved.
