### ISSUE TITLE
self_mute is not defined

### ISSUE THREAD

**Issue by lztqq** [Aspect1103/Lavapy#7]
Newest commit changed argument names of the function Player.play, however the function still uses self_mute and self_deaf instead of selfMute and selfDeaf

Error:
File "...\Python310\lib\site-packages\lavapy\player.py", line 279, in connect
    await self.guild.change_voice_state(channel=self.channel, self_mute=self_mute, self_deaf=self_deaf)

**Comment by JackAshwell11** [comment]
Should be fixed now with v1.6.1.
